#!/usr/bin/env python3
"""Generate src/data/words.js from the system dictionary.

Source: /usr/share/dict/words -> web2 (Webster's Second, public domain).
Deliberately NOT the New York Times Wordle list, which is their property.

web2 omits almost all inflected forms, so a raw extract rejects real guesses
like SEALS, LIKED or TRIES. We derive the high-precision ones and keep a small
hand-written supplement for irregulars and words postdating 1934.
"""
import re, sys

lines = [w.strip() for w in open('/usr/share/dict/words')]
low = lambda n: {w for w in lines if re.fullmatch(r'[a-z]{%d}' % n, w)}   # lowercase == not a proper noun
three, four, five = low(3), low(4), low(5)

derived = set()
derived |= {w + 's'  for w in four}                          # cat -> cats
derived |= {w + 'd'  for w in four if w.endswith('e')}       # like -> liked
derived |= {w + 'ed' for w in three if not w.endswith('e')}  # ask -> asked
derived |= {w[:-1] + 'ies' for w in three if w.endswith('y')}  # try -> tries

# irregulars and modern words web2 predates
SUPPLEMENT = """
began begun broke drove froze spoke stole swore wrote arose awoke
women proud quiet eaten taken shown known grown blown flown drawn
email debug cache proxy login admin pixel modem vlogs blogs
pizza salsa sushi tacos donut bagel mocha latte curry ramen
condo motel disco radar laser scuba video audio combo turbo
gonna wanna kinda howdy vibes memes emoji selfie
fjord ninja nacho zilch pesto sushi ramen bagel mocha vodka kebab scone wafer
yodel zesty quark nomad koala llama gecko hyena igloo jumbo rhino sloth tapir
""".split()
SUPPLEMENT = [w for w in SUPPLEMENT if re.fullmatch(r'[a-z]{5}', w)]

ANSWERS = sorted({w for w in open(sys.argv[1]).read().split() if re.fullmatch(r'[a-z]{5}', w)})

allowed = {w for w in (five | derived | set(SUPPLEMENT) | set(ANSWERS)) if len(w) == 5}

open('src/data/words.js', 'w').write(
  "/* GENERATED by scripts/build_words.py -- do not edit by hand.\n"
  "   Guesses: Webster's Second (public domain) five-letter words, plus derived\n"
  "   inflections and a small modern supplement. Not the NYT Wordle list.\n"
  "   Answers: a curated common-word subset, so no archaic entries come up. */\n"
  "export const ALLOWED = new Set(\n  '" + ' '.join(sorted(allowed)) + "'.split(' ')\n);\n\n"
  "export const ANSWERS =\n  '" + ' '.join(ANSWERS) + "'.split(' ');\n")

print(f'allowed {len(allowed)} (web2 {len(five)} + derived {len(derived - five)} + supplement)')
print(f'answers {len(ANSWERS)}')
bad = [w for w in ANSWERS if w not in allowed]
print('answers not guessable:', bad or 'none')
