#!/usr/bin/env python3
"""Generate src/sprites/run-footprint.js from the run sprite strip.

The capybara's silhouette is much wider than its ground footprint: the nose
reaches the front of the cell while the front paw stops 8px short. A single
box either kills you with the bush under your chin, or lets a tall bush pass
through the chest. So we store, per frame, the horizontal extent of the sprite
over the bottom k rows -- then the collision box is chosen by how tall the
obstacle actually is.
"""
from PIL import Image
import sys

im = Image.open(sys.argv[1] if len(sys.argv) > 1 else '/tmp/run5.png').convert('RGBA')
W, H = im.size
px = im.load()
CW = 27
frames = W // CW

table = []
for f in range(frames):
    x0 = f * CW
    rows = []
    lo, hi = 10**9, -1
    for k in range(1, H + 1):                      # k = number of rows up from the bottom
        y = H - k
        for x in range(CW):
            if px[x0 + x, y][3] > 0:
                lo = min(lo, x); hi = max(hi, x)
        rows.append((lo, hi) if hi >= 0 else (0, -1))   # empty: nothing at this height yet
    table.append(rows)

body = ',\n  '.join(
    '[' + ','.join(f'{lo},{hi}' for lo, hi in rows) + ']' for rows in table
)
open('src/sprites/run-footprint.js', 'w').write(
    "/* GENERATED by scripts/build_footprint.py -- do not edit by hand.\n"
    "   FOOTPRINT[frame] is a flat [lo,hi, lo,hi, ...] list: entry k-1 is the\n"
    "   sprite's horizontal extent over the bottom k rows of its 27x21 cell.\n"
    "   Used so the collision box matches what the obstacle can actually touch. */\n"
    f"export const FRAME_ROWS = {H};\nexport const FRAME_COLS = {CW};\n"
    f"export const FOOTPRINT = [\n  {body},\n];\n\n"
    "/* null when the sprite has no pixels that low (mid-stride, feet in the air) */\n"
    "export function extentAt(frame, rowsUp){\n"
    "  const f = FOOTPRINT[frame % FOOTPRINT.length];\n"
    "  const k = Math.max(1, Math.min(FRAME_ROWS, Math.ceil(rowsUp))) - 1;\n"
    "  const lo = f[k * 2], hi = f[k * 2 + 1];\n"
    "  return hi < lo ? null : [lo, hi];\n"
    "}\n\n"
    "/* World-space [back, front] of the part of the sprite an obstacle of this\n"
    "   height can actually reach, or null if it cannot reach the sprite at all. */\n"
    "export function hitBox(frame, obstacleH, spriteY, scale, cx){\n"
    "  const rowsUp = (obstacleH - spriteY) / scale;\n"
    "  if (rowsUp <= 0) return null;\n"
    "  const ext = extentAt(frame, rowsUp);\n"
    "  if (!ext) return null;\n"
    "  const cellL = cx - FRAME_COLS / 2 * scale;\n"
    "  return [cellL + ext[0] * scale, cellL + (ext[1] + 1) * scale];\n"
    "}\n"
)
for f, rows in enumerate(table):
    print(f'frame {f}: bottom-1-row {rows[0]}  bottom-6 {rows[5]}  full {rows[-1]}')
